from enum import Enum as StrEnum

class ErrorCode(StrEnum):
    PRODUCT_CREATE_FAILED = "PRODUCT_CREATE_FAILED"
    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
    RESOURCE_NOT_FOUND = "Resource not found"

    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_SVC_TIMEOUT = "USER_SERVICE_TIMEOUT"
    USER_SVC_UNAVAILABLE = "USER_SERVICE_UNAVAILABLE"
    USER_SVC_ERROR = "USER_SERVICE_ERROR"
    USER_INVALID_DATA = "USER_INVALID_DATA",
    USER_BLOCKED = "USER_BLOCKED",

    ORDER_CREATE_FAILED = "ORDER_CREATE_FAILED"
    ORDER_SVC_ERROR = "ORDER_SVC_ERROR"
